'use client';

import { useState, useRef, useEffect } from 'react';
import { Bot, User, Send, Sparkles, X, ArrowRight } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Task, Agent, ProjectStage } from '@/lib/types';

interface PlanningChatProps {
    onClose: () => void;
    onUpdateGhostTasks: (tasks: Task[]) => void;
    onConfirmPlan: (tasks: Task[]) => void;
}

interface Message {
    id: string;
    role: 'user' | 'agent';
    content: string;
    timestamp: number;
}

export function PlanningChat({ onClose, onUpdateGhostTasks, onConfirmPlan }: PlanningChatProps) {
    const [messages, setMessages] = useState<Message[]>([
        {
            id: '1',
            role: 'agent',
            content: "Hello! I'm your Project Manager. To get started, tell me what you want to build. I'll help break it down into actionable tasks.",
            timestamp: Date.now()
        }
    ]);
    const [inputValue, setInputValue] = useState('');
    const [isTyping, setIsTyping] = useState(false);
    const messagesEndRef = useRef<HTMLDivElement>(null);

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    };

    useEffect(() => {
        scrollToBottom();
    }, [messages]);

    const handleSendMessage = async () => {
        if (!inputValue.trim()) return;

        const userMsg: Message = {
            id: Date.now().toString(),
            role: 'user',
            content: inputValue,
            timestamp: Date.now()
        };

        setMessages(prev => [...prev, userMsg]);
        setInputValue('');
        setIsTyping(true);

        // Simulate AI processing
        setTimeout(() => {
            const agentMsg: Message = {
                id: (Date.now() + 1).toString(),
                role: 'agent',
                content: "I've drafted some tasks based on your requirements. Ghost tasks have been added to the board. Does this look correct?",
                timestamp: Date.now()
            };
            setMessages(prev => [...prev, agentMsg]);
            setIsTyping(false);

            // Generate Ghost Tasks
            const ghosts: Task[] = [
                { id: 'ghost-1', projectId: 'current', title: 'Define Data Schema', description: 'Generated by AI', status: 'todo', priority: 'HIGH', createdAt: new Date().toISOString() },
                { id: 'ghost-2', projectId: 'current', title: 'Setup Authentication', description: 'Generated by AI', status: 'todo', priority: 'HIGH', createdAt: new Date().toISOString() },
                { id: 'ghost-3', projectId: 'current', title: 'Design Dashboard UI', description: 'Generated by AI', status: 'todo', priority: 'MEDIUM', createdAt: new Date().toISOString() },
                { id: 'ghost-4', projectId: 'current', title: 'API Integration', description: 'Generated by AI', status: 'in_progress', priority: 'MEDIUM', createdAt: new Date().toISOString() },
            ];
            onUpdateGhostTasks(ghosts);
        }, 1500);
    };

    const handleConfirm = () => {
        // In a real app, we would take the ghost tasks
        const ghosts: Task[] = [
            { id: `new-${Date.now()}-1`, projectId: 'current', title: 'Define Data Schema', description: 'Generated by AI', status: 'todo', priority: 'HIGH', createdAt: new Date().toISOString() },
            { id: `new-${Date.now()}-2`, projectId: 'current', title: 'Setup Authentication', description: 'Generated by AI', status: 'todo', priority: 'HIGH', createdAt: new Date().toISOString() },
            { id: `new-${Date.now()}-3`, projectId: 'current', title: 'Design Dashboard UI', description: 'Generated by AI', status: 'todo', priority: 'MEDIUM', createdAt: new Date().toISOString() },
            { id: `new-${Date.now()}-4`, projectId: 'current', title: 'API Integration', description: 'Generated by AI', status: 'in_progress', priority: 'MEDIUM', createdAt: new Date().toISOString() },
        ];
        onConfirmPlan(ghosts);
    };

    return (
        <div className="flex flex-col h-full bg-secondary/30 border-l border-white/5 w-96 shrink-0 transition-all">
            {/* Header */}
            <div className="p-4 border-b border-white/5 flex items-center justify-between bg-secondary/50">
                <div className="flex items-center gap-3">
                    <div className="h-8 w-8 rounded-full bg-primary/20 flex items-center justify-center border border-primary/30">
                        <Bot className="h-4 w-4 text-primary" />
                    </div>
                    <div>
                        <h3 className="font-semibold text-sm">AI Project Kickoff</h3>
                        <p className="text-xs text-muted-foreground">Planning Assistant</p>
                    </div>
                </div>
                <button onClick={onClose} className="p-1.5 hover:bg-white/10 rounded-lg text-muted-foreground hover:text-foreground">
                    <X className="h-4 w-4" />
                </button>
            </div>

            {/* Messages */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4">
                {messages.map((msg) => (
                    <div
                        key={msg.id}
                        className={cn(
                            "flex gap-3 max-w-[90%]",
                            msg.role === 'user' ? "ml-auto flex-row-reverse" : ""
                        )}
                    >
                        <div className={cn(
                            "h-8 w-8 rounded-full flex items-center justify-center shrink-0 border",
                            msg.role === 'user' ? "bg-white/10 border-white/5" : "bg-primary/20 border-primary/30"
                        )}>
                            {msg.role === 'user' ? <User className="h-4 w-4" /> : <Bot className="h-4 w-4 text-primary" />}
                        </div>
                        <div className={cn(
                            "p-3 rounded-2xl text-sm",
                            msg.role === 'user'
                                ? "bg-primary text-primary-foreground rounded-tr-none"
                                : "bg-white/10 text-foreground rounded-tl-none"
                        )}>
                            {msg.content}
                        </div>
                    </div>
                ))}
                {isTyping && (
                    <div className="flex gap-3 max-w-[90%] animate-pulse">
                        <div className="h-8 w-8 rounded-full bg-primary/20 flex items-center justify-center shrink-0 border border-primary/30">
                            <Bot className="h-4 w-4 text-primary" />
                        </div>
                        <div className="bg-white/10 p-3 rounded-2xl rounded-tl-none flex gap-1 items-center h-10">
                            <div className="w-1.5 h-1.5 bg-muted-foreground rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                            <div className="w-1.5 h-1.5 bg-muted-foreground rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                            <div className="w-1.5 h-1.5 bg-muted-foreground rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                        </div>
                    </div>
                )}
                <div ref={messagesEndRef} />
            </div>

            {/* Footer */}
            <div className="p-4 border-t border-white/5 space-y-3 bg-secondary/30">
                {/* Quick Actions (Mock) */}
                <div className="flex gap-2 overflow-x-auto pb-2 scrollbar-hide">
                    {['Generate Roadmap', 'Suggest Tech Stack', 'Identify Risks'].map(action => (
                        <button key={action} className="whitespace-nowrap px-3 py-1.5 rounded-full bg-white/5 border border-white/5 text-xs hover:bg-white/10 transition-colors">
                            {action}
                        </button>
                    ))}
                </div>

                <div className="flex gap-2">
                    <input
                        value={inputValue}
                        onChange={(e) => setInputValue(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
                        placeholder="Describe your project goal..."
                        className="flex-1 bg-black/20 border border-white/10 rounded-xl px-4 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                    <button
                        onClick={handleSendMessage}
                        disabled={!inputValue.trim() || isTyping}
                        className="p-2 bg-primary text-primary-foreground rounded-xl hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        <Send className="h-4 w-4" />
                    </button>
                </div>

                <button
                    onClick={handleConfirm}
                    className="w-full flex items-center justify-center gap-2 py-2.5 bg-green-500/10 text-green-500 border border-green-500/20 rounded-xl hover:bg-green-500/20 transition-all font-medium text-sm"
                >
                    <Sparkles className="h-4 w-4" /> Confirm & Create Tasks
                </button>
            </div>
        </div>
    );
}
